"""Add product table for shopping intelligence

Revision ID: 0bbe492c3cdf
Revises: f90f34d9b4cf
Create Date: 2025-06-26 22:13:39.999177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import outfitai_project


# revision identifiers, used by Alembic.
revision: str = '0bbe492c3cdf'
down_revision: Union[str, Sequence[str], None] = 'f90f34d9b4cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('product_url', sa.String(), nullable=False),
    sa.Column('retailer', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('fit', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_url', name='_product_url_uc')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_color'), ['color'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_fit'), ['fit'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_material'), ['material'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_product_url'), ['product_url'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_retailer'), ['retailer'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_retailer'))
        batch_op.drop_index(batch_op.f('ix_products_product_url'))
        batch_op.drop_index(batch_op.f('ix_products_material'))
        batch_op.drop_index(batch_op.f('ix_products_gender'))
        batch_op.drop_index(batch_op.f('ix_products_fit'))
        batch_op.drop_index(batch_op.f('ix_products_color'))
        batch_op.drop_index(batch_op.f('ix_products_category'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    # ### end Alembic commands ###
