"""Add wardrobe suggestion engine models and fields

Revision ID: 8aca955eadb1
Revises: 79d8c516d7d1
Create Date: 2025-08-24 22:44:24.038948

"""
from typing import Sequence, Union
import outfitai_project
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8aca955eadb1'
down_revision: Union[str, Sequence[str], None] = '79d8c516d7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worn_outfit_history',
    sa.Column('id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('user_id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('item_ids', sa.String(), nullable=False),
    sa.Column('event_context', sa.String(), nullable=True),
    sa.Column('worn_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('style', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('added_method', sa.Enum('TEXT', 'IMAGE', 'VOICE', 'MANUAL', name='addedmethod'), nullable=True))
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('TOP', 'BOTTOM', 'OUTERWEAR', 'SHOES', 'ACCESSORY', 'DRESS', 'FULL_BODY', 'TRADITIONAL', 'OTHER', name='itemcategory'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=sa.Enum('TOP', 'BOTTOM', 'OUTERWEAR', 'SHOES', 'ACCESSORY', 'DRESS', 'FULL_BODY', 'TRADITIONAL', 'OTHER', name='itemcategory'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
        batch_op.drop_column('added_method')
        batch_op.drop_column('style')

    op.drop_table('worn_outfit_history')
    # ### end Alembic commands ###
