"""Add user_events table for interaction logging

Revision ID: 9d5a4b92db70
Revises: 0bbe492c3cdf
Create Date: 2025-06-27 01:28:42.843660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import outfitai_project


# revision identifiers, used by Alembic.
revision: str = '9d5a4b92db70'
down_revision: Union[str, Sequence[str], None] = '0bbe492c3cdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_events',
    sa.Column('id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('user_id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_events_event_type'), ['event_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_events_event_type'))

    op.drop_table('user_events')
    # ### end Alembic commands ###
