"""Initial migration with cross-database GUID

Revision ID: f90f34d9b4cf
Revises: 
Create Date: 2025-06-23 14:37:23.780450

"""
from typing import Sequence, Union
import outfitai_project
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90f34d9b4cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('age_range', sa.String(), nullable=True),
    sa.Column('body_type', sa.Enum('ECTOMORPH', 'MESOMORPH', 'ENDOMORPH', 'UNSPECIFIED', name='bodytype'), nullable=True),
    sa.Column('body_measurements', sa.String(), nullable=True),
    sa.Column('skin_tone', sa.Enum('WARM', 'COOL', 'NEUTRAL', 'UNSPECIFIED', name='skintone'), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('generated_recommendations',
    sa.Column('id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('user_id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('event_type_context', sa.String(), nullable=True),
    sa.Column('style_goal_context', sa.String(), nullable=True),
    sa.Column('inspirational_image_source_info', sa.String(), nullable=True),
    sa.Column('analyzed_inspirational_image_description', sa.Text(), nullable=True),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('overall_reasoning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wardrobe_items',
    sa.Column('id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('user_id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('TOP', 'BOTTOM', 'OUTERWEAR', 'SHOES', 'ACCESSORY', 'DRESS', 'OTHER', name='itemcategory'), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('material', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.Column('last_worn', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wardrobe_items_name'), ['name'], unique=False)

    op.create_table('saved_outfits',
    sa.Column('id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('user_id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('recommendation_id', outfitai_project.db.orm_models.GUID(length=32), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=True),
    sa.Column('user_rating', sa.Integer(), nullable=True),
    sa.Column('user_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['recommendation_id'], ['generated_recommendations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_outfits')
    with op.batch_alter_table('wardrobe_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wardrobe_items_name'))

    op.drop_table('wardrobe_items')
    op.drop_table('generated_recommendations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
